<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CaptureViewer</RootNamespace>
    <!-- <ApplicationIcon>app.ico</ApplicationIcon> -->
  </PropertyGroup>
  <ItemGroup>
    <None Update="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project> 